# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70b226066f7d61c67385f82467b0673ed721832710e87cf06d49ebd4601233d0ccd8f44d2d9cbf810e8b7c9454d3b96cd2e28bb4de529c0dce53fc803a49d9ea

test:
  secret_key_base: 7f53de989d56673000fc0342bedb86116a233b952700b413af671c0890a14d8f80c6f1cfc2984b55a91946aaf7ffd61a318c674f665febdf0c36ff404b24fbca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
